return {
	-- Brainrot God
	"Espresso Signora",
	"Nuclearo Dinossauro",
	"Cocofanto Elefanto",
	"To to to Sahur",
	"Tralalita Tralala",
	"Tralalero Tralala",
	"Chihuanini Taconini",
	"Crabbo Limonetta",
	"Los Crocodillitos",
	"Los Bombinitos",
	"Los Tralaleritos",
	"Graipuss Medussi",
	"Los Tacoritas",
	"Los Tipi Tacos",
	"Los Tungtungtungcitos",
	"Los Orcalitos",
	"Los Noobinis",
	"Las Tralaleritas",
	"Las Sis",
	"Las Capuchinas",
	"Los Matteos",
	"Spioniro Golubiro",
	"Brr es Teh Patipum",
	"Caramello Filtrello",
	"Los Bros",
	"Trippi Troppi Troppa Trippa",
	"Orcalero Orcala",
	"Alessio",
	"Fragola La La La",
	"Girafa Celestre",
	"Trenostruzzo Turbo 3000",
	"Gattito Tacoto",
	"Dul Dul Dul",
	"Tralaledon",
	"Tigroligre Frutonni",
	"Chimpanzini Spiderini",
	"Gattatino Neonino",
	"Brainrot God Lucky Block",

	-- Secret
	"Pot Hotspot",
	"Agarrini la Palini",
	"Blackhole Goat",
	"Chachechi",
	"Celularcini Viciosini",
	"Bulbito Bandito Traktorito",
	"Esok Sekolah",
	"Chicleteira Bicicleteira",
	"Cacasito Satalito",
	"Los Nooo My Hotspotsitos",
	"Los Chicleteiras",
	"La Vacca Saturno Saturnita",
	"Matteo",
	"La Sahur Combinasion",
	"Guerriro Digitale",
	"Pakrahmatmamat",
	"Las Vaquitas Saturnitas",
	"Extinct Tralalero",
	"Garama and Madundung",
	"Los orcaleritos dicen",
	"Antonio",
	"Ketupat Kepat",
	"La Cucaracha",
	"Job Job Job Sahur",
	"Ketchuru and Musturu",
	"Karkerkar Kurkur",
	"Extinct Matteo",
	"Extinct Ballerina",
	"Torrtuginni Dragonfrutini",
	"Secret Lucky Block",
}
