return {

	["Club"] = {
		DisplayName = "Club",
		Price = 0,
		Purchasable = false,
		PassId = nil,
		RebrithRequire = 0,
		ImageId = 0,
		Description = nil,
		EquipedOnce = false,
		Info = {
			HitboxSize = Vector3.new(4,4.5,7.6),
			HitboxOffset = CFrame.new(0,0,-2.5),
			HitboxDuration = .2,
			Cooldown = .8,
			Power = 40,
			Ragdoll = 2,--duration du ragdoll
		},
	},
	
	["BearTrap"] = {
		DisplayName = "Bear Trap",
		Price = 5000,
		Purchasable = true,
		PassId = nil,
		RebrithRequire = 1,
		ImageId = 0,
		Description = nil,
		EquipedOnce = false,
		MaxUse = 1,
		Info = {},
	},
	
	["BasicGlove"] = {
		DisplayName = "Basic Glove",
		Price = 1000,
		Purchasable = true,
		PassId = nil,
		RebrithRequire = 1,
		ImageId = 0,
		Description = nil,
		EquipedOnce = false,
		MaxUse = 1,
		Info = {},
	},

	["BrickGlove"] = {
		DisplayName = "Brick Glove",
		Price = 1000000,
		Purchasable = true,
		PassId = nil,
		RebrithRequire = 4,
		ImageId = 0,
		Description = nil,
		EquipedOnce = false,
		MaxUse = 1,
		Info = {},
	},

	["InvisibleGlove"] = {
		DisplayName = "Invisible Glove",
		Price = 700000,
		Purchasable = true,
		PassId = nil,
		RebrithRequire = 7,
		ImageId = 0,
		Description = nil,
		EquipedOnce = false,
		MaxUse = 1,
		Info = {},
	},

	["LightGlove"] = {
		DisplayName = "Light Glove",
		Price = 100000000,
		Purchasable = true,
		PassId = nil,
		RebrithRequire = 10,
		ImageId = 0,
		Description = nil,
		EquipedOnce = false,
		MaxUse = 1,
		Info = {},
	},
	["SpeedCoil"] = {
		DisplayName = "Speed Coil",
		Price = 50000,
		Purchasable = true,
		PassId = nil,
		RebrithRequire = 3,
		ImageId = 0,
		Description = nil,
		EquipedOnce = false,
		MaxUse = 1,
		Info = {},
	},
	["GravityCoil"] = {
		DisplayName = "Gravity Coil",
		Price = 10000,
		Purchasable = true,
		PassId = nil,
		RebrithRequire = 2,
		ImageId = 0,
		Description = nil,
		EquipedOnce = false,
		MaxUse = 1,
		Info = {},
	},
	["SuperSpeedCoil"] = {
		DisplayName = "Super Speed Coil",
		Price = 10000000,
		Purchasable = true,
		PassId = nil,
		RebrithRequire = 10,
		ImageId = 0,
		Description = nil,
		EquipedOnce = false,
		MaxUse = 1,
		Info = {},
	},
	["DoubleCoil"] = {
		DisplayName = "Double Coil",
		Price = 1000000,
		Purchasable = true,
		PassId = nil,
		RebrithRequire = 8,
		ImageId = 0,
		Description = nil,
		EquipedOnce = false,
		MaxUse = 1,
		Info = {},
	},
	["Sentry"] = {
		DisplayName = "Sentry",
		Price = 500000,
		Purchasable = true,
		PassId = nil,
		RebrithRequire = 6,
		ImageId = 0,
		Description = nil,
		EquipedOnce = false,
		MaxUse = 1,
		Info = {},
	},
	["Taser"] = {
		DisplayName = "Taser",
		Price = 100000,
		Purchasable = true,
		PassId = nil,
		RebrithRequire = 5,
		ImageId = 0,
		Description = nil,
		EquipedOnce = false,
		MaxUse = 1,
		Info = {},
	},
	["InvisibilityCloak"] = {
		DisplayName = "Invisibility Cloak",
		Price = 200000,
		Purchasable = true,
		PassId = nil,
		RebrithRequire = 5,
		ImageId = 0,
		Description = nil,
		EquipedOnce = false,
		MaxUse = 1,
		Info = {},
	},
	["GrappleHook"] = {
		DisplayName = "Grapple Hook",
		Price = 500000,
		Purchasable = true,
		PassId = nil,
		RebrithRequire = 7,
		ImageId = 0,
		Description = nil,
		EquipedOnce = false,
		MaxUse = 1,
		Info = {},
	},
	["BoomBox"] = {
		DisplayName = "BoomBox",
		Price = 1,
		Purchasable = false,
		PassId = nil,
		RebrithRequire = 0,
		ImageId = 104878720334895,
		Description = nil,
		EquipedOnce = false,
		MaxUse = 1,
		Info = {},
	},
	["Flying Carpet"] = {
		DisplayName = "Flying Carpet",
		Price = 1,
		Purchasable = false,
		PassId = nil,
		RebrithRequire = 0,
		ImageId = 0,
		Description = nil,
		EquipedOnce = false,
		MaxUse = 1,
		Info = {},
	},
}