local CmdrTypeLists = {}

CmdrTypeLists.BrainrotNames = {
	"67",
	"Admin Lucky Block",
	"Agarrini la Palini",
	"Alessio",
	"Antonio",
	"Avocadini Antilopini",
	"Avocadini Guffo",
	"Avocadorilla",
	"Ballerina Cappuccina",
	"Ballerino Lololo",
	"Bambini Crostini",
	"Bananita Dolphinita",
	"Bandito Axolito",
	"Bandito Bobritto",
	"Betonini Spyderini",
	"Bisonte Giuppitere",
	"Blackhole Goat",
	"Blueberrinni Octopusini",
	"Bombardiro Crocodilo",
	"Bombombini Gusini",
	"Boneca Ambalabu",
	"Brainrot God Lucky Block",
	"Brr Brr Patapim",
	"Brr es Teh Patipum",
	"Brri Brri Bicus Dicus Bombicus",
	"Bulbito Bandito Traktorito",
	"Burbaloni Loliloli",
	"Cacasito Satalito",
	"Cacto Hipopotamo",
	"Cappuccino Assassino",
	"Caramello Filtrello",
	"Carloo",
	"Carrotini Brainini",
	"Cavallo Virtuoso",
	"Celularcini Viciosini",
	"Chachechi",
	"Chef Crabracadabra",
	"Chicleteira Bicicleteira",
	"Chihuanini Taconini",
	"Chimpanzini Bananini",
	"Chimpanzini Spiderini",
	"Cocofanto Elefanto",
	"Cocosini Mama",
	"Crabbo Limonetta",
	"Dragon Cannelloni",
	"Dug dug dug",
	"Dul Dul Dul",
	"Esok Sekolah",
	"Espresso Signora",
	"Extinct Ballerina",
	"Extinct Matteo",
	"Extinct Tralalero",
	"Fluriflura",
	"Fragola La La La",
	"Frigo Camelo",
	"Ganganzelli Trulala",
	"Gangster Footera",
	"Garama and Madundung",
	"Gattatino Neonino",
	"Gattatino Nyanino",
	"Gattito Tacoto",
	"Girafa Celestre",
	"Glorbo Fruttodrillo",
	"Gorillo Watermelondrillo",
	"Graipuss Medussi",
	"Guerriro Digitale",
	"Job Job Job Sahur",
	"Karkerkar Kurkur",
	"Ketchuru and Musturu",
	"Ketupat Kepat",
	"La Cucaracha",
	"La Extinct Grande",
	"La Grande Combinasion",
	"La Karkerkar Combinasion",
	"La Sahur Combinasion",
	"La Vacca Saturno Saturnita",
	"Las Capuchinas",
	"Las Sis",
	"Las Tralaleritas",
	"Las Vaquitas Saturnitas",
	"Lerulerulerule",
	"Lionel Cactuseli",
	"Lirili Larila",
	"Los Bombinitos",
	"Los Boneca_AmbalabuDouble dicen BONECAA",
	"Los Boneca_Ambalabusitos dicen AMBALABUU",
	"Los Bros",
	"Los Chicleteiras",
	"Los Combinasionas",
	"Los Crocodillitos",
	"Los Garama_And_Madungdung Sitos dicen GARAM AND MADU",
	"Los Mateositos dicen MATEOO",
	"Los Matteos",
	"Los Noobinis",
	"Los Nooo My Hotspotsitos",
	"Los orcaleritos dicen",
	"Los Orcalitos",
	"Los Pot Hotspotsitos dicen HOTSPOTT",
	"Los Ta ta Tasitos dicen Sahur",
	"Los Tacoritas",
	"Los Tipi Tacos",
	"Los Tralaleritos",
	"Los tung tungDouble Dicen sahurr",
	"Los Tungtungtungcitos",
	"Matteo",
	"Mythic Lucky Block",
	"Noobini Pizzanini",
	"Nuclearo Dinossauro",
	"Odin Din Din Dun",
	"Orangutini Ananassini",
	"Orcalero Orcala",
	"Pakrahmatmamat",
	"Pandaccini Bananini",
	"Penguino Cocosino",
	"Perochello Lemonchello",
	"Piccione Macchina",
	"Pipi Avocado",
	"Pipi Corni",
	"Pipi Kiwi",
	"Pipi Potato",
	"Pot Hotspot",
	"Quivioli Ameleonni",
	"Rhino Toasterino",
	"Salamino Penguino",
	"Secret Lucky Block",
	"Sigma Boy",
	"Sigma Girl",
	"Spaghetti Tualetti",
	"Spioniro Golubiro",
	"Strawberrelli Flamingelli",
	"Strawberry Elephant",
	"Svinina Bombardino",
	"Ta Ta Ta Ta Sahur",
	"Taco Lucky Block",
	"Talpa Di Fero",
	"Te Te Te Sahur",
	"Ti Ti Ti Sahur",
	"Tigrilini Watermelini",
	"Tigroligre Frutonni",
	"Tim Cheese",
	"Tipi Topi Taco",
	"To to to Sahur",
	"Torrtuginni Dragonfrutini",
	"Tracoducotulu Delapeladustuz",
	"Tralaledon",
	"Tralalero Tralala",
	"Tralalita Tralala",
	"Trenostruzzo Turbo 3000",
	"Tric Trac Baraboom",
	"Trippi Troppi",
	"Trippi Troppi Troppa Trippa",
	"Trulimero Trulicina",
	"Tukanno Bananno",
	"Tung Tung Tung Sahur",
	"Unclito Samito",
	"Urubini Flamenguini",
	"Zibra Zubra Zibralini",
}

CmdrTypeLists.Mutations = {
	"BubbleGum",
	"Diamond",
	"Electric",
	"Freeze",
	"Gold",
	"Normal",
	"Shiny",
	"Solar",
	"Spectral",
	"Volcan",
}

CmdrTypeLists.MapMutations = {
	"Normal",
	"BubbleGum",
	"Freeze",
	"Solar",
	"Spectral",
	"Volcan",
}

CmdrTypeLists.MapMutationScopes = {
	"Local",
	"Global",
}

CmdrTypeLists.AdminAbuses = {
	"Normal",
	"Disco",
}

CmdrTypeLists.Auras = {
	"67",
	"Aqua",
	"Aurora_Stars",
	"Blessed",
	"Bubble",
	"Choosen_One",
	"Dark_Chakra",
	"Electric",
	"Energy_Release",
	"Fire_and_Ice",
	"Galactic",
	"Hellfire",
	"Ice",
	"Idol",
	"Imaginary_Technique",
	"JoyBoy",
	"Light",
	"Lucifer",
	"New_Flame",
	"Pink_Matter",
	"Power_Source",
	"Sea_King",
	"Shadowed",
	"Shield",
	"Sin_Of_Pride",
	"Slash_King",
	"Smokey",
	"SSJ",
	"Thunder",
	"Tornado",
	"Ultra_Instinct",
	"Unlocked",
	"Waterslash",
	"Wind",
}

CmdrTypeLists.TypesList = {
	"Default",
	"Delete",
	"All",
	"AllDelete",
}

CmdrTypeLists.GlobaleTypesList = {
	"Mess",
	"LuckServer",
	"Events",
}

CmdrTypeLists.ColorList = {
	"Red",
	"Blue",
	"White",
	"Black",
	"Green",
	"Yellow",
	"Orange",
	"Purple",
	"Pink",
	"Brown",
	"Gray",
	"LightGray",
	"DarkGray",
	"Cyan",
	"Magenta",
	"Lime",
	"Teal",
	"Navy",
	"Maroon",
	"Olive",
	"Gold",
	"Silver",
	"Beige",
	"Turquoise",
	"Indigo",
	"Violet",
	"Coral",
	"Salmon",
	"Crimson",
	"Khaki",
	"Mint",
	"Peach",
	"Lavender",
	"Aqua",
	"SkyBlue",
	"DarkBlue",
	"DarkGreen",
	"LightBlue",
	"LightGreen",
}

return CmdrTypeLists
